### ISSUE TITLE
Problem with tweeting

### ISSUE THREAD

**Issue by Permanently** [mispy/ebooks_example#16]
Hey! :)
So I just updated ebooks from v2.2.5 to v3.1.0 and I've updated the configurations to the new versions as well (from what I can see on the github file)
I'm getting this whenever I try `ebooks tweet model/name.model botname`

```
Building: sentence 0 of 1228
/var/lib/gems/2.1.0/gems/twitter_ebooks-3.1.6/bin/ebooks:247:in `tweet': undefined method `configure' for nil:NilClass (NoMethodError)
        from /var/lib/gems/2.1.0/gems/twitter_ebooks-3.1.6/bin/ebooks:412:in `command'
        from /var/lib/gems/2.1.0/gems/twitter_ebooks-3.1.6/bin/ebooks:429:in `<top (required)>'
        from /usr/local/bin/ebooks:23:in `load'
        from /usr/local/bin/ebooks:23:in `<main>'
```

Is there a solution, or have I done something wrong?

**Comment by ghost** [comment]
Either you're giving the wrong username to `ebooks tweet` or the bot username isn't configured correctly. I'll add a proper error message for that situation :)

**Comment by Permanently** [comment]
```
pi@raspberrypi:~/pepper $ ebooks tweet model/pepper.model cpepperebooks
Building: sentence 0 of 1228
/var/lib/gems/2.1.0/gems/twitter_ebooks-3.1.6/bin/ebooks:247:in `tweet': undefined method `configure' for nil:NilClass (NoMethodError)
        from /var/lib/gems/2.1.0/gems/twitter_ebooks-3.1.6/bin/ebooks:412:in `command'
        from /var/lib/gems/2.1.0/gems/twitter_ebooks-3.1.6/bin/ebooks:429:in `<top (required)>'
        from /usr/local/bin/ebooks:23:in `load'
        from /usr/local/bin/ebooks:23:in `<main>'
```

This must be right, surely :/ is the username case-sensitive?

**Comment by Permanently** [comment]
Okay, I just tried it and the username is case-sensitive. Thanks for the feedback :)

**Comment by ghost** [comment]
I've made it case insensitive in master now, just in case anyone else has a similar problem!
