### ISSUE TITLE
Crash on DM from non-follower

### ISSUE THREAD

**Issue by dfoxfranke** [mispy/ebooks_example#3]
The bot crashes if it attempts to reply to a DM from someone who doesn't follow it:

    /var/lib/gems/1.9.1/gems/twitter-4.8.1/lib/twitter/response/raise_error.rb:21:in `on_complete': You cannot send messages to users who are not following you. (Twitter::Error::Forbidden)
        from /var/lib/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'
        from /var/lib/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'
        from /var/lib/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
        from /var/lib/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/request/url_encoded.rb:15:in `call'
        from /var/lib/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/request/multipart.rb:14:in `call'
        from /var/lib/gems/1.9.1/gems/twitter-4.8.1/lib/twitter/request/multipart_with_file.rb:14:in `call'
        from /var/lib/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
        from /var/lib/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
        from /var/lib/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `post'
        from /var/lib/gems/1.9.1/gems/twitter-4.8.1/lib/twitter/client.rb:108:in `request'
        from /var/lib/gems/1.9.1/gems/twitter-4.8.1/lib/twitter/client.rb:72:in `post'
        from /var/lib/gems/1.9.1/gems/twitter-4.8.1/lib/twitter/api/utils.rb:82:in `object_from_response'
        from /var/lib/gems/1.9.1/gems/twitter-4.8.1/lib/twitter/api/direct_messages.rb:141:in `direct_message_create'
        from /var/lib/gems/1.9.1/gems/twitter_ebooks-2.2.5/lib/twitter_ebooks/bot.rb:144:in `reply'
        from /home/dafranke/ebooks_example/bots.rb:30:in `block (2 levels) in initialize'
        from /var/lib/gems/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `call'
        from /var/lib/gems/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
        from /var/lib/gems/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'}}}

**Comment by ghost** [comment]
I think twitter changed the DM behavior so this no longer happens (you can reply to a sent DM even if you couldn't normally initiate a DM conversation)
